/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCProxy_H
#define RPCProxy_H

#include <thrift/TDispatchProcessor.h>
#include "RPCProxy_types.h"

namespace rpcproxy {

class RPCProxyIf {
 public:
  virtual ~RPCProxyIf() {}
  virtual void hello() = 0;
  virtual void fetchURLContent(std::string& _return, const std::string& url) = 0;
};

class RPCProxyIfFactory {
 public:
  typedef RPCProxyIf Handler;

  virtual ~RPCProxyIfFactory() {}

  virtual RPCProxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RPCProxyIf* /* handler */) = 0;
};

class RPCProxyIfSingletonFactory : virtual public RPCProxyIfFactory {
 public:
  RPCProxyIfSingletonFactory(const boost::shared_ptr<RPCProxyIf>& iface) : iface_(iface) {}
  virtual ~RPCProxyIfSingletonFactory() {}

  virtual RPCProxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RPCProxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<RPCProxyIf> iface_;
};

class RPCProxyNull : virtual public RPCProxyIf {
 public:
  virtual ~RPCProxyNull() {}
  void hello() {
    return;
  }
  void fetchURLContent(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};


class RPCProxy_hello_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  RPCProxy_hello_args() {
  }

  virtual ~RPCProxy_hello_args() throw() {}


  bool operator == (const RPCProxy_hello_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RPCProxy_hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RPCProxy_hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RPCProxy_hello_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~RPCProxy_hello_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RPCProxy_hello_result {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  RPCProxy_hello_result() {
  }

  virtual ~RPCProxy_hello_result() throw() {}


  bool operator == (const RPCProxy_hello_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RPCProxy_hello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RPCProxy_hello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RPCProxy_hello_presult {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~RPCProxy_hello_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RPCProxy_fetchURLContent_args__isset {
  _RPCProxy_fetchURLContent_args__isset() : url(false) {}
  bool url;
} _RPCProxy_fetchURLContent_args__isset;

class RPCProxy_fetchURLContent_args {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  RPCProxy_fetchURLContent_args() : url() {
  }

  virtual ~RPCProxy_fetchURLContent_args() throw() {}

  std::string url;

  _RPCProxy_fetchURLContent_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const RPCProxy_fetchURLContent_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const RPCProxy_fetchURLContent_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RPCProxy_fetchURLContent_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RPCProxy_fetchURLContent_pargs {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};


  virtual ~RPCProxy_fetchURLContent_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RPCProxy_fetchURLContent_result__isset {
  _RPCProxy_fetchURLContent_result__isset() : success(false) {}
  bool success;
} _RPCProxy_fetchURLContent_result__isset;

class RPCProxy_fetchURLContent_result {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};

  RPCProxy_fetchURLContent_result() : success() {
  }

  virtual ~RPCProxy_fetchURLContent_result() throw() {}

  std::string success;

  _RPCProxy_fetchURLContent_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const RPCProxy_fetchURLContent_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RPCProxy_fetchURLContent_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RPCProxy_fetchURLContent_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RPCProxy_fetchURLContent_presult__isset {
  _RPCProxy_fetchURLContent_presult__isset() : success(false) {}
  bool success;
} _RPCProxy_fetchURLContent_presult__isset;

class RPCProxy_fetchURLContent_presult {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};


  virtual ~RPCProxy_fetchURLContent_presult() throw() {}

  std::string* success;

  _RPCProxy_fetchURLContent_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RPCProxyClient : virtual public RPCProxyIf {
 public:
  RPCProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RPCProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello();
  void send_hello();
  void recv_hello();
  void fetchURLContent(std::string& _return, const std::string& url);
  void send_fetchURLContent(const std::string& url);
  void recv_fetchURLContent(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RPCProxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RPCProxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RPCProxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_fetchURLContent(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RPCProxyProcessor(boost::shared_ptr<RPCProxyIf> iface) :
    iface_(iface) {
    processMap_["hello"] = &RPCProxyProcessor::process_hello;
    processMap_["fetchURLContent"] = &RPCProxyProcessor::process_fetchURLContent;
  }

  virtual ~RPCProxyProcessor() {}
};

class RPCProxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RPCProxyProcessorFactory(const ::boost::shared_ptr< RPCProxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RPCProxyIfFactory > handlerFactory_;
};

class RPCProxyMultiface : virtual public RPCProxyIf {
 public:
  RPCProxyMultiface(std::vector<boost::shared_ptr<RPCProxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RPCProxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RPCProxyIf> > ifaces_;
  RPCProxyMultiface() {}
  void add(boost::shared_ptr<RPCProxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void hello() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello();
    }
    ifaces_[i]->hello();
  }

  void fetchURLContent(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->fetchURLContent(_return, url);
    }
    ifaces_[i]->fetchURLContent(_return, url);
    return;
  }

};

} // namespace

#endif
