/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCProxy_CONSTANTS_H
#define RPCProxy_CONSTANTS_H

#include "RPCProxy_types.h"

namespace rpcproxy {

class RPCProxyConstants {
 public:
  RPCProxyConstants();

};

extern const RPCProxyConstants g_RPCProxy_constants;

} // namespace

#endif
