/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCProxy_constants.h"

namespace rpcproxy {

const RPCProxyConstants g_RPCProxy_constants;

RPCProxyConstants::RPCProxyConstants() {
}

} // namespace

